services:
    rag:
        build:
            context: .
            dockerfile: Dockerfile
        # target: runtime # nếu dùng multi-stage (ở dưới)
        image: rag-course:latest
        env_file: .env.example
        environment:
            PYTHONUNBUFFERED: "1"
            PYTHONPATH: /app
            # UVICORN
            HOST: 0.0.0.0
            PORT: "8000"
        ports:
            - "8000:8000"
        volumes:
            - ./storage:/app/storage # persist Chroma
            - ./data:/app/data # dữ liệu vào/ra
            - ./scripts:/app/scripts # dễ chỉnh script
        command: ["bash","-lc","uvicorn src.api:app --host ${HOST:-0.0.0.0} --port ${PORT:-8000} --workers 2"]
        healthcheck:
            test: ["CMD-SHELL", "curl -sf http://localhost:8000/metrics >/dev/null || exit 1"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 20s
        restart: unless-stopped
        user: "1000:1000" # tránh ghi file root-owned vào ./storage, ./data
        # GPU (tùy chọn): bật các dòng sau khi chạy trên máy có NVIDIA + nvidia-container-runtime
        # deploy:
        # resources:
        # reservations:
        # devices:
        # - capabilities: ["gpu"]


networks:
    default:
        name: rag-net